name: podfy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-261.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  audioplayers: ^0.20.1
  path_provider: ^2.0.7
  permission_handler: ^8.3.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
